# Dockerfile
FROM php:8.2-apache

# Mở port 80
EXPOSE 80

# Cài thêm các extension nếu cần (ví dụ mysqli)
# RUN docker-php-ext-install mysqli

# Copy file config Apache nếu muốn tùy chỉnh
# COPY my-apache.conf /etc/apache2/sites-available/000-default.conf